from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    api_port: int = 8000

    postgres_user: str = "postgres"
    postgres_password: str = "postgres"
    postgres_db: str = "omr_db_v2"
    postgres_host: str = "localhost"
    postgres_port: int = 5434

    jwt_secret_key: str
    jwt_algorithm: str = "HS256"
    access_token_expire_minutes: int = 15
    refresh_token_expire_days: int = 7

    smtp_email: str = ""
    smtp_password: str = ""

    minio_endpoint: str = "localhost:9000"
    minio_access_key: str = "minioadmin"
    minio_secret_key: str = "minioadmin"
    minio_bucket: str = "omr-sheets"
    minio_secure: bool = False

    # Directory holding MobileNetV3_scripted.pt + name_reco_labels.json
    # (generated by scripts/build_recognition_assets.py).
    recognition_models_dir: str = "recognition_models"

    # When True, /upload-images rejects scans that can't be segmented up front
    # (reported as failedSheets) instead of storing/grading them.
    segmentation_precheck: bool = True

    # Answer-bubble grading models (YOLOv8 detector + filled/empty CNN).
    bubble_yolo_path: str = "recognition_models/bubble_yolo.pt"
    bubble_cnn_path: str = "recognition_models/bubble_cnn_scripted.pt"
    # YOLO confidence / NMS thresholds for bubble detection.
    bubble_conf_threshold: float = 0.30
    bubble_iou_threshold: float = 0.30
    # Min filled/empty decision confidence (max(p, 1-p)) for a bubble to be
    # trusted. A question with a bubble below this — or a double-mark — is
    # flagged for human review.
    bubble_review_threshold: float = 0.80

    @property
    def database_url(self) -> str:
        from urllib.parse import quote_plus

        password = quote_plus(self.postgres_password)
        return (
            f"postgresql+asyncpg://{self.postgres_user}:{password}"
            f"@{self.postgres_host}:{self.postgres_port}/{self.postgres_db}"
        )

    @property
    def database_url_sync(self) -> str:
        from urllib.parse import quote_plus

        password = quote_plus(self.postgres_password)
        return (
            f"postgresql+psycopg2://{self.postgres_user}:{password}"
            f"@{self.postgres_host}:{self.postgres_port}/{self.postgres_db}"
        )


settings = Settings()
